services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    env_file:
      - .keycloak.env
    ports:
      - "8080:8080"
    command:
      - start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data/
volumes:
  keycloak_data:
